/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CheckRequest */
        CheckRequest: {
            /** Side A */
            side_a: components["schemas"]["TextInput"] | components["schemas"]["UrlInput"];
            /**
             * Side B
             * @default null
             */
            side_b: (components["schemas"]["TextInput"] | components["schemas"]["UrlInput"]) | null;
            /** @default compare */
            mode: components["schemas"]["Mode"];
            /**
             * Include Paraphrase
             * @default true
             */
            include_paraphrase: boolean;
            /**
             * Include Layout
             * @default false
             */
            include_layout: boolean;
            /** @default balanced */
            strictness: components["schemas"]["Strictness"];
        };
        /** CheckResult */
        CheckResult: {
            /**
             * Overall Similarity
             * @description Share of side A covered by any match.
             */
            overall_similarity: number;
            side_a: components["schemas"]["SideResult"];
            /** @default null */
            side_b: components["schemas"]["SideResult"] | null;
            /** Passages */
            passages: components["schemas"]["MatchedPassage"][];
            /** Sources */
            sources: components["schemas"]["Source"][];
            /**
             * @description Null when layout comparison was off or not possible.
             * @default null
             */
            layout: components["schemas"]["LayoutScores"] | null;
        };
        /** HighlightSpan */
        HighlightSpan: {
            /** Start */
            start: number;
            /** End */
            end: number;
            kind: components["schemas"]["MatchKind"];
            /** Passage Id */
            passage_id: string;
        };
        /** Job */
        Job: {
            /** Id */
            id: string;
            status: components["schemas"]["JobStatus"];
            /**
             * Progress
             * @default 0
             */
            progress: number;
            /**
             * Error
             * @default null
             */
            error: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * JobStatus
         * @enum {string}
         */
        JobStatus: "queued" | "fetching" | "comparing" | "done" | "failed";
        /** LayoutScores */
        LayoutScores: {
            /** Overall */
            overall: number;
            /** Grid */
            grid: number;
            /** Type Scale */
            type_scale: number;
            /** Components */
            components: number;
            /** Palette */
            palette: number;
        };
        /**
         * MatchKind
         * @enum {string}
         */
        MatchKind: "near_identical" | "paraphrased";
        /** MatchedPassage */
        MatchedPassage: {
            /** Id */
            id: string;
            kind: components["schemas"]["MatchKind"];
            /** Similarity */
            similarity: number;
            /**
             * Text
             * @description The passage as it appears in side A.
             */
            text: string;
            /** Source Id */
            source_id: string;
            /**
             * Source Url
             * Format: uri
             */
            source_url: string;
            /**
             * Published Date
             * @description When the source page was first published, if known.
             * @default null
             */
            published_date: string | null;
            /**
             * Edit Summary
             * @default null
             */
            edit_summary: string | null;
        };
        /**
         * Mode
         * @enum {string}
         */
        Mode: "compare" | "discover";
        /**
         * SideResult
         * @description One side as it was compared: the extracted text the spans index into.
         */
        SideResult: {
            /** Text */
            text: string;
            /**
             * Url
             * @description Set when the side was submitted as a URL.
             * @default null
             */
            url: string | null;
            /** Word Count */
            word_count: number;
            /**
             * Spans
             * @default []
             */
            spans: components["schemas"]["HighlightSpan"][];
        };
        /** Source */
        Source: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Domain */
            domain: string;
            /**
             * Pct Of A
             * @description Share of side A assigned to this source; spans are never double counted.
             */
            pct_of_a: number;
        };
        /**
         * Strictness
         * @enum {string}
         */
        Strictness: "lenient" | "balanced" | "strict";
        /** TextInput */
        TextInput: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "text";
            /** Text */
            text: string;
        };
        /** UrlInput */
        UrlInput: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "url";
            /**
             * Url
             * Format: uri
             */
            url: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
